In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df=pd.read_csv(r"D:\DATA ANALYSIS\Meta Ads Campaign Performance Analysis\Data\Cleaned files\meta_ads_cleaned.csv")

In [6]:
df

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,creative_type,CTR,CPC,CPA,CVR,CPL,ROI,ROAS,Frequency,Decision
0,C027,Hyderabad Conversion,Interest - Technology,Facebook,Leads,COMPLETED,2026-02-18,2026-02-25,83426,68019,...,Video,0.52,7.16,1557.16,0.46,311.43,-19.45,0.81,1.23,Discontinue
1,C055,Ahmedabad Sales,Lookalike 1%,Instagram,Leads,PAUSED,2026-04-18,2026-05-06,107945,72764,...,Image,0.68,7.55,691.76,1.09,307.45,-79.09,0.21,1.48,Discontinue
2,C050,Jaipur Lead Generation,Interest - Technology,Instagram,Conversions,ACTIVE,2026-01-14,2026-02-10,14694,13073,...,Image,1.31,30.75,NaN,0.00,269.79,15.13,1.15,1.12,Pause
3,C093,Mumbai Sales,Interest - Technology,Facebook,Leads,ACTIVE,2026-04-25,2026-05-22,230437,198773,...,Reel,1.17,1.93,113.44,1.70,57.98,-10.40,0.90,1.16,Discontinue
4,C151,Mumbai Sales,Interest - Business,Instagram,Leads,PAUSED,2026-01-15,2026-02-12,239711,197146,...,Reel,0.87,1.63,141.01,1.16,27.97,16.91,1.17,1.22,Continue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,C202,Pune Education,Lookalike 1%,Instagram,Sales,PAUSED,2026-02-27,2026-03-07,228309,165885,...,Video,0.27,5.00,510.45,0.98,65.16,-29.22,0.71,1.38,Discontinue
253,C169,Hyderabad Conversion,Engaged Users,Instagram,Traffic,PAUSED,2026-04-04,2026-05-05,159526,136594,...,Reel,0.88,1.42,77.16,1.84,14.33,-78.20,0.22,1.17,Discontinue
254,C186,Hyderabad Conversion,Broad Audience,Facebook,Traffic,ACTIVE,2026-06-22,2026-07-12,50000,42394,...,Image,1.22,9.58,450.88,2.12,189.08,18.86,1.19,1.18,Continue
255,C036,Pune Education,Retargeting,Facebook,Conversions,COMPLETED,2026-05-31,2026-06-11,105814,59807,...,Reel,0.71,8.16,1536.27,0.53,149.88,-15.00,0.85,1.77,Discontinue
256,C130,Kolkata Awareness,Interest - Business,Instagram,Conversions,PAUSED,2026-03-21,2026-04-05,135832,83336,...,Video,0.89,1.52,229.01,0.66,59.10,-70.44,0.30,1.63,Discontinue

In [7]:
print(df.shape)

(257, 32)

In [8]:
df.head()

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,creative_type,CTR,CPC,CPA,CVR,CPL,ROI,ROAS,Frequency,Decision
0,C027,Hyderabad Conversion,Interest - Technology,Facebook,Leads,COMPLETED,2026-02-18,2026-02-25,83426,68019,...,Video,0.52,7.16,1557.16,0.46,311.43,-19.45,0.81,1.23,Discontinue
1,C055,Ahmedabad Sales,Lookalike 1%,Instagram,Leads,PAUSED,2026-04-18,2026-05-06,107945,72764,...,Image,0.68,7.55,691.76,1.09,307.45,-79.09,0.21,1.48,Discontinue
2,C050,Jaipur Lead Generation,Interest - Technology,Instagram,Conversions,ACTIVE,2026-01-14,2026-02-10,14694,13073,...,Image,1.31,30.75,NaN,0.00,269.79,15.13,1.15,1.12,Pause
3,C093,Mumbai Sales,Interest - Technology,Facebook,Leads,ACTIVE,2026-04-25,2026-05-22,230437,198773,...,Reel,1.17,1.93,113.44,1.70,57.98,-10.40,0.90,1.16,Discontinue
4,C151,Mumbai Sales,Interest - Business,Instagram,Leads,PAUSED,2026-01-15,2026-02-12,239711,197146,...,Reel,0.87,1.63,141.01,1.16,27.97,16.91,1.17,1.22,Continue

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       257 non-null    str
 1   campaign_name     257 non-null    str
 2   adset             257 non-null    str
 3   platform          257 non-null    str
 4   objective         257 non-null    str
 5   status            257 non-null    str
 6   start_date        257 non-null    str
 7   end_date          257 non-null    str
 8   impressions       257 non-null    int64
 9   reach             257 non-null    int64
 10  clicks            257 non-null    int64
 11  spend             257 non-null    float64
 12  leads             257 non-null    int64
 13  purchases         257 non-null    int64
 14  revenue           257 non-null    float64
 15  conversion_value  257 non-null    float64
 16  country           257 non-null    str
 17  region            254 non-null    str
 18  age_group         257 non-null    str
 19  gender            257 non-null    str
 20  placement         257 non-null    str
 21  device            257 non-null    str
 22  creative_type     257 non-null    str
 23  CTR               257 non-null    float64
 24  CPC               257 non-null    float64
 25  CPA               243 non-null    float64
 26  CVR               257 non-null    float64
 27  CPL               257 non-null    float64
 28  ROI               257 non-null    float64
 29  ROAS              257 non-null    float64
 30  Frequency         257 non-null    float64
 31  Decision          257 non-null    str
dtypes: float64(11), int64(5), str(16)
memory usage: 98.0 KB

In [10]:
# Check for nulls

In [11]:
df.isnull().sum()

campaign_id          0
campaign_name        0
adset                0
platform             0
objective            0
status               0
start_date           0
end_date             0
impressions          0
reach                0
clicks               0
spend                0
leads                0
purchases            0
revenue              0
conversion_value     0
country              0
region               3
age_group            0
gender               0
placement            0
device               0
creative_type        0
CTR                  0
CPC                  0
CPA                 14
CVR                  0
CPL                  0
ROI                  0
ROAS                 0
Frequency            0
Decision             0
dtype: int64

In [12]:
# Check Decision distribution

In [13]:
df['Decision'].value_counts()

Decision
Discontinue    168
Continue        55
Pause           34
Name: count, dtype: int64

In [14]:
#convert dates

In [15]:
df['start_date'] = pd.to_datetime(df['start_date'])
df['end_date']   = pd.to_datetime(df['end_date'])

In [16]:
# Create a new column: how many days did the campaign run?

In [17]:
df['duration_days'] = (df['end_date'] - df['start_date']).dt.days

In [18]:
# Summary statistics

In [19]:
df[['spend','revenue','clicks','leads','purchases','CTR','CPC','CVR','ROI','ROAS']].describe().round(2)

,spend,revenue,clicks,leads,purchases,CTR,CPC,CVR,ROI,ROAS
count,257.00,257.00,257.00,257.00,257.00,257.00,257.00,257.00,257.00,257.00
mean,3586.25,4213.82,1315.09,139.11,38.70,1.04,8.03,1.58,21.24,1.21
std,1683.14,7131.19,1459.82,285.17,114.08,0.88,22.29,1.86,180.18,1.80
min,709.63,189.20,17.00,1.00,0.00,0.25,0.10,0.00,-91.40,0.09
25%,2168.47,1116.34,476.00,24.00,3.00,0.54,1.65,0.63,-57.62,0.42
50%,3469.53,2253.60,965.00,62.00,9.00,0.86,3.52,1.20,-26.02,0.74
75%,5071.95,4215.71,1674.00,139.00,21.00,1.17,7.89,1.74,16.21,1.16
max,6496.65,50465.25,10015.00,2174.00,796.00,4.49,322.00,8.99,891.07,9.91

In [20]:
# fix "Nan" strings

In [21]:
df['region'] = df['region'].replace('Nan', np.nan)
df['objective'] = df['objective'].replace('Nan', np.nan)
df['placement'] = df['placement'].replace('Nan', np.nan)
df['adset'] = df['adset'].replace('Nan', np.nan)

In [22]:
# confirm no duplicate campaign IDs

In [23]:
print("Duplicate IDs:", df['campaign_id'].duplicated().sum())

Duplicate IDs: 0

In [24]:
#overall business KPIs

In [25]:
total_spend   = df['spend'].sum()
total_revenue = df['revenue'].sum()
total_leads   = df['leads'].sum()
total_purch   = df['purchases'].sum()
overall_roi  = ((total_revenue - total_spend) / total_spend) * 100
overall_roas = total_revenue / total_spend

print(f"Total Spend:    ₹{total_spend:,.2f}")
print(f"Total Revenue:  ₹{total_revenue:,.2f}")
print(f"Total Leads:    {total_leads:,}")
print(f"Total Purchases:{total_purch:,}")
print(f"Overall ROI:    {overall_roi:.2f}%")
print(f"Overall ROAS:   {overall_roas:.2f}x")

Total Spend:    ₹921,666.16
Total Revenue:  ₹1,082,951.97
Total Leads:    35,752
Total Purchases:9,947
Overall ROI:    17.50%
Overall ROAS:   1.17x

In [26]:
#how much money is stuck where?

In [27]:
decision_summary= df.groupby('Decision').agg({'campaign_id':'count','spend':'sum','revenue':'sum','leads':'sum','purchases':'sum'}).rename(columns={'campaign_id':'campaigns'})

decision_summary['ROI_%'] = ((decision_summary['revenue'] - decision_summary['spend'])/ decision_summary['spend'] * 100).round(2)

print(decision_summary)

             campaigns      spend    revenue  leads  purchases   ROI_%
Decision
Continue            55  179272.17  608346.92  21118       7826  239.34
Discontinue        168  609345.47  317196.45  12282       1974  -47.94
Pause               34  133048.52  157408.60   2352        147   18.31

In [28]:
#Top 10 Performers by ROI

In [29]:
top_roi = df.nlargest(10,'ROI')[['campaign_id','campaign_name','region','platform','adset','spend','revenue','ROI','ROAS','CPC','CVR']]
top_roi = top_roi.sort_values(by='revenue', ascending=False)

print(top_roi)

    campaign_id         campaign_name     region   platform  \
117        C207  Hyderabad Conversion  Hyderabad  Instagram
159        C132     Kolkata Awareness    Kolkata   Facebook
210        C182   Gurgaon Performance    Gurgaon  Instagram
21         C085      Lucknow Lead Gen    Lucknow  Instagram
217        C023    Delhi Ncr Lead Gen  Delhi Ncr   Facebook
23         C102          Mumbai Sales     Mumbai  Instagram
131        C257  Hyderabad Conversion  Hyderabad  Instagram
245        C056      Noida Conversion      Noida   Facebook
173        C094  Bangalore Tech Leads  Bangalore   Facebook
33         C145   Gurgaon Performance    Gurgaon   Facebook

                     adset    spend   revenue     ROI  ROAS   CPC   CVR
117  Interest - Technology  5870.40  50465.25  759.66  8.60  2.63  7.00
159       Website Visitors  5071.95  50166.79  889.10  9.89  0.57  8.87
210            Retargeting  4300.38  42619.91  891.07  9.91  0.72  7.76
21             Retargeting  4467.61  41337.35  825.27  9.25  3.49  5.93
217           Lookalike 1%  3314.03  23679.16  614.51  7.15  0.40  8.03
23            Lookalike 1%  2590.79  18683.69  621.16  7.21  1.68  7.31
131  Interest - Technology  2273.45  16480.91  624.93  7.25  0.33  7.15
245           Lookalike 1%  1881.01  16065.32  754.08  8.54  0.69  8.52
173       Website Visitors  1278.10   9802.03  666.92  7.67  1.12  6.11
33        Website Visitors  1137.16   9190.03  708.16  8.08  0.25  5.70

In [30]:
#Worst Performers

In [31]:
#High spend + negative ROI

In [32]:
red_flags = df[(df['spend']>4000)&(df['ROI']<0)].sort_values('spend',ascending=False)

print((red_flags[['campaign_id','campaign_name','region','spend','revenue','ROI','Decision']]).head(15))
print(f"\n Wsate spend on red flags: ₹{red_flags['spend'].sum():,.2f}")

    campaign_id           campaign_name     region    spend  revenue    ROI  \
84         C081     Chennai Retargeting    Chennai  6469.27  4430.46 -31.52
138        C142    Bangalore Tech Leads  Bangalore  6433.90  2044.65 -68.22
20         C041         Ahmedabad Sales  Ahmedabad  6422.46  3583.58 -44.20
155        C249     Gurgaon Performance    Gurgaon  6361.54  3098.22 -51.30
228        C048          Pune Education       Pune  6359.27  2171.00 -65.86
196        C208       Kolkata Awareness    Kolkata  6331.13  4475.88 -29.30
154        C121     Chennai Retargeting    Chennai  6226.95  6044.92  -2.92
255        C036          Pune Education       Pune  6145.07  5223.31 -15.00
234        C141      Delhi Ncr Lead Gen  Delhi Ncr  6132.68  1805.88 -70.55
219        C100         Ahmedabad Sales  Ahmedabad  6128.07   841.36 -86.27
15         C067            Mumbai Sales     Mumbai  6101.17  5134.04 -15.85
227        C028    Hyderabad Conversion  Hyderabad  6097.97  3942.41 -35.35
61         C217          Pune Education       Pune  6079.27   677.99 -88.85
139        C220  Jaipur Lead Generation     Jaipur  6039.86  1655.85 -72.58
115        C256     Chennai Retargeting    Chennai  5943.05  1265.04 -78.71

        Decision
84   Discontinue
138  Discontinue
20   Discontinue
155  Discontinue
228  Discontinue
196  Discontinue
154  Discontinue
255  Discontinue
234  Discontinue
219  Discontinue
15   Discontinue
227  Discontinue
61   Discontinue
139  Discontinue
115  Discontinue

 Wsate spend on red flags: ₹365,435.24

In [33]:
#zero-purchase campaigns

In [34]:
zero_pur = df[(df['purchases'] == 0) & (df['spend'] > 2000)]

print(zero_pur[['campaign_id','campaign_name','region','spend','revenue','purchases','ROI','Decision']])
print(f"Campaigns with 0 purchases & spend > ₹2000: {len(zero_pur)}")
print(f"Total wasted: ₹{zero_pur['spend'].sum():,.2f}")

    campaign_id           campaign_name     region    spend  revenue  \
2          C050  Jaipur Lead Generation     Jaipur  5935.39  6833.65
16         C033         Ahmedabad Sales  Ahmedabad  3127.93  2863.58
28         C149      Delhi Ncr Lead Gen  Delhi Ncr  5348.59  4543.76
38         C127        Noida Conversion      Noida  2467.29  1068.72
81         C054  Jaipur Lead Generation     Jaipur  3771.34  4655.77
96         C197  Jaipur Lead Generation     Jaipur  2101.51  1823.24
123        C034     Chennai Retargeting    Chennai  4484.61  5822.60
133        C236        Lucknow Lead Gen    Lucknow  5850.34  7452.30
170        C095  Jaipur Lead Generation     Jaipur  2749.36  2567.28
179        C030  Jaipur Lead Generation     Jaipur  5474.02  1656.93
191        C199            Mumbai Sales     Mumbai  2235.88  1193.65
200        C013       Kolkata Awareness    Kolkata  3378.54  2707.15
214        C188          Pune Education       Pune  3729.06  2485.02

     purchases    ROI     Decision
2            0  15.13        Pause
16           0  -8.45  Discontinue
28           0 -15.05  Discontinue
38           0 -56.68  Discontinue
81           0  23.45        Pause
96           0 -13.24  Discontinue
123          0  29.84        Pause
133          0  27.38        Pause
170          0  -6.62  Discontinue
179          0 -69.73  Discontinue
191          0 -46.61  Discontinue
200          0 -19.87  Discontinue
214          0 -33.36  Discontinue
Campaigns with 0 purchases & spend > ₹2000: 13
Total wasted: ₹50,653.86

In [35]:
#Multi-Level Analysis

In [36]:
#Platform

In [37]:
platform_perf = df.groupby('platform').agg({'spend':'sum','revenue':'sum','clicks':'sum','purchases':'sum','CTR':'mean','CPC':'mean','ROI':'mean'}).round(2)

print(platform_perf)

               spend    revenue  clicks  purchases   CTR    CPC   ROI
platform
Facebook   463471.60  544016.22  163986       5071  1.06  10.21  21.4
Instagram  458194.56  538935.75  173993       4876  1.02   5.99  21.1

In [38]:
#Region

In [39]:
region_perf = df.groupby('region').agg({'spend':'sum','revenue':'sum','ROI':'mean','CPC':'mean','CVR':'mean'}).round(2).sort_values('ROI', ascending=False)
print(region_perf)

              spend    revenue     ROI    CPC   CVR
region
Gurgaon    31864.50   80675.00  157.58   2.58  2.91
Bangalore  55164.34   81829.23   96.29   6.49  2.35
Lucknow    79700.41  147398.02   73.15   4.74  2.03
Noida      75054.27   96591.17   39.81   6.81  1.77
Hyderabad  99889.85  138942.52   35.65   5.41  1.71
Mumbai     78920.99   92022.75   34.08   5.83  1.72
Kolkata    78732.93  122160.23   28.22   5.29  1.96
Delhi Ncr  99212.11   85626.12  -10.34   8.60  1.43
Jaipur     78783.89   59923.30  -19.89  21.23  0.98
Chennai    70402.91   57440.00  -23.91  10.59  0.99
Pune       98888.66   74537.36  -26.34   8.02  1.15
Ahmedabad  67198.07   43103.30  -33.18   6.47  0.92

In [40]:
#Ad Set

In [41]:
adset_perf = df.groupby('adset').agg({'spend':'sum','revenue':'sum','CTR':'mean','CVR':'mean','ROI':'mean'}).round(2).sort_values('ROI', ascending=False)

print(adset_perf)

                           spend    revenue   CTR   CVR    ROI
adset
Retargeting            106515.58  166129.89  1.12  1.60  58.65
Lookalike 1%           143670.70  186577.84  1.15  2.05  48.82
Website Visitors       159133.16  227541.45  1.17  1.76  47.00
Interest - Technology  150923.69  179308.55  1.04  1.40  18.00
Engaged Users           84921.81   81187.72  0.98  1.31  -2.79
Broad Audience         150524.84  146800.25  0.88  1.40 -10.88
Interest - Business    115529.38   89021.28  0.95  1.35 -13.72

In [42]:
#Creative Type

In [43]:
creative_perf = df.groupby('creative_type').agg({'spend':'sum','revenue':'sum','CTR':'mean','ROI':'mean'}).round(2).sort_values('ROI', ascending=False)

print(creative_perf)

                   spend    revenue   CTR    ROI
creative_type
Video          328948.51  420850.56  1.09  30.06
Image          297211.14  395446.49  1.00  27.55
Carousel       161450.87  173342.95  1.09  26.11
Reel           134055.64   93311.97  0.98 -22.41

In [44]:
#Age × Gender

In [45]:
age_gender = df.pivot_table(values='ROI', index='age_group',columns='gender', aggfunc='mean').round(2)

print(age_gender)

gender       All  Female   Male
age_group
18-24      59.60   18.62 -28.86
25-34      23.80  112.69 -33.81
35-44      27.14  -35.06 -29.85
45-54      34.89   61.27  -1.05
55+        34.36  -19.94  20.14

In [46]:
#Device & Placement

In [47]:
print("Device:\n", df.groupby('device')[['CTR','CVR','ROI']].mean().round(2))
print("\nPlacement:\n", df.groupby('placement')[['CTR','CVR','ROI']].mean().round(2))

Device:
           CTR   CVR    ROI
device
Desktop  1.11  1.68  25.18
Mobile   1.03  1.60  22.28
Tablet   0.91  0.82 -14.14

Placement:
                     CTR   CVR    ROI
placement
Audience Network   1.16  1.88  38.44
Facebook Feed      0.86  1.32  -0.11
Facebook Stories   1.05  1.62  32.11
Instagram Feed     0.93  0.94 -25.78
Instagram Stories  1.07  1.94  32.42
Reels              1.12  1.55  27.83

In [48]:
#Export

In [49]:
with pd.ExcelWriter("D:\DATA ANALYSIS\Meta Ads Campaign Performance Analysis\Outputs\excel files\Meta_Ads_Report.xlsx", engine='openpyxl') as writer:
    df.to_excel(writer, sheet_name='Cleaned_Data', index=False)
    decision_summary.to_excel(writer, sheet_name='Decision_Summary')
    platform_perf.to_excel(writer, sheet_name='Platform_Perf')
    region_perf.to_excel(writer, sheet_name='Region_Perf')
    adset_perf.to_excel(writer, sheet_name='Adset_Perf')
    creative_perf.to_excel(writer, sheet_name='Creative_Perf')
    top_roi.to_excel(writer, sheet_name='Top_10_ROI', index=False)
    red_flags.to_excel(writer, sheet_name='Red_Flags', index=False)

In [50]:
# CSV files for Power BI

In [51]:
df.to_csv("D:\DATA ANALYSIS\Meta Ads Campaign Performance Analysis\Outputs\csv files for power bi\powerbi_main.csv", index=False)
region_perf.to_csv("powerbi_region.csv")
platform_perf.to_csv("powerbi_platform.csv")
decision_summary.to_csv("powerbi_decision.csv")
print("CSV files saved for Power BI")

CSV files saved for Power BI